apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: initial-app
  description: An example of a Backstage application.
  annotations:
    jira/project-key: this-is-my-pro
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
